apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fabrick
spec:
  destination:
    name: ''
    namespace: ''
    server: ''
  source:
    path: /fabrick
    repoURL: 'https://github.com/lerudinegueye/fabrick'
    targetRevision: HEAD
    directory:
      recurse: false
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false